#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.FrontEndManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UserAccess")]
	public partial class DashBoardsDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_dashboarduser(tbl_dashboarduser instance);
    partial void Updatetbl_dashboarduser(tbl_dashboarduser instance);
    partial void Deletetbl_dashboarduser(tbl_dashboarduser instance);
    #endregion
		
		public DashBoardsDatabaseDataContext() : 
				base(global::Deg.FrontEndManager.Properties.Settings.Default.UserAccessConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DashBoardsDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashBoardsDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashBoardsDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashBoardsDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_dashboarduser> tbl_dashboardusers
		{
			get
			{
				return this.GetTable<tbl_dashboarduser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_dashboarduser")]
	public partial class tbl_dashboarduser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<long> _marketaccess;
		
		private System.Nullable<System.DateTime> _lastaccess;
		
		private string _lastlayout;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnmarketaccessChanging(System.Nullable<long> value);
    partial void OnmarketaccessChanged();
    partial void OnlastaccessChanging(System.Nullable<System.DateTime> value);
    partial void OnlastaccessChanged();
    partial void OnlastlayoutChanging(string value);
    partial void OnlastlayoutChanged();
    #endregion
		
		public tbl_dashboarduser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketaccess", DbType="BigInt")]
		public System.Nullable<long> marketaccess
		{
			get
			{
				return this._marketaccess;
			}
			set
			{
				if ((this._marketaccess != value))
				{
					this.OnmarketaccessChanging(value);
					this.SendPropertyChanging();
					this._marketaccess = value;
					this.SendPropertyChanged("marketaccess");
					this.OnmarketaccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastaccess", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastaccess
		{
			get
			{
				return this._lastaccess;
			}
			set
			{
				if ((this._lastaccess != value))
				{
					this.OnlastaccessChanging(value);
					this.SendPropertyChanging();
					this._lastaccess = value;
					this.SendPropertyChanged("lastaccess");
					this.OnlastaccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlayout", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string lastlayout
		{
			get
			{
				return this._lastlayout;
			}
			set
			{
				if ((this._lastlayout != value))
				{
					this.OnlastlayoutChanging(value);
					this.SendPropertyChanging();
					this._lastlayout = value;
					this.SendPropertyChanged("lastlayout");
					this.OnlastlayoutChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
