//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.FrontEndWebServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deg.FrontEndWebServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div ng-view ng-controller=&quot;baldayMonitorController&quot; ng-init=&quot;initialize(&apos;ADA20289-0579-4E01-A02D-E11C7C977173&apos;);&quot; style=&quot;width:inherit;height:inherit;white-space:nowrap;overflow:scroll;&quot;&gt;
        ///    &lt;fieldset class=&quot;groupbox fixedsize1&quot; style=&quot;white-space:normal;&quot;&gt;
        ///        &lt;legend&gt;Ref Days&lt;/legend&gt;
        ///        &lt;jqx-date-time-input jqx-width=&quot;100&quot; ng-model=&quot;textboxdate&quot; jqx-settings=&quot;dateformat&quot;&gt;&lt;/jqx-date-time-input&gt;
        ///        &lt;jqx-button ng-click=&quot;onAddDateClick();&quot; jqx-width=&quot;45&quot; jqx-height=&quot;25&quot; style=&quot;margin-top [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaldayMonitor {
            get {
                return ResourceManager.GetString("BaldayMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div ng-view ng-controller=&quot;baldayMonitorController&quot; ng-init=&quot;initialize();&quot; style=&quot;width:inherit;height:inherit;white-space:nowrap;overflow:scroll;&quot;&gt;
        ///    &lt;jqx-grid jqx-settings=&quot;tablesettings&quot;&gt;&lt;/jqx-grid&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string PjmDispatch {
            get {
                return ResourceManager.GetString("PjmDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div ng-controller=&quot;tickMonitorController&quot; ng-init=&quot;initialize(&apos;ADA20289-0579-4E01-A02D-E11C7C977173&apos;)&quot; style=&quot;width:inherit;height:inherit;overflow:scroll;&quot;&gt;
        ///    &lt;jqx-tabs jqx-width=&apos;300&apos; jqx-height=&apos;300&apos;&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;Tick&lt;/li&gt;
        ///            &lt;li&gt;Dispatch Rate&lt;/li&gt;
        ///        &lt;/ul&gt;
        ///        &lt;div&gt;
        ///            &lt;fieldset class=&quot;groupbox&quot; style=&quot;width:250px;height:60px;&quot;&gt;
        ///                &lt;legend jqx-ng-model&gt;{{timezone}} Time&lt;/legend&gt;
        ///                &lt;label style=&quot;align-items:center;&quot; jqx-ng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TickMonitor {
            get {
                return ResourceManager.GetString("TickMonitor", resourceCulture);
            }
        }
    }
}
