#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.DatabaseManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ERCOT")]
	public partial class ERCOT5minLMPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ERCOT5minLMPDataContext() : 
				base(global::Deg.DatabaseManager.Properties.Settings.Default.ERCOTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ERCOT5minLMPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERCOT5minLMPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERCOT5minLMPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERCOT5minLMPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ERCOT.dbo.GetERCOT5minLMPStartStop")]
		public ISingleResult<GetERCOT5minLMPStartStopResult> GetERCOT5minLMPStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StopDate", DbType="DateTime")] System.Nullable<System.DateTime> stopDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, stopDate);
			return ((ISingleResult<GetERCOT5minLMPStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ERCOT.dbo.GetERCOTLocations")]
		public ISingleResult<GetERCOTLocationsResult> GetERCOTLocations()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetERCOTLocationsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ERCOT.dbo.GetMax5minLMPTimepoint")]
		public ISingleResult<GetMax5minLMPTimepointResult> GetMax5minLMPTimepoint()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMax5minLMPTimepointResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetERCOT5minLMPStartStopResult
	{
		
		private System.DateTime _timepoint_cpt;
		
		private string _name;
		
		private decimal _lmp;
		
		public GetERCOT5minLMPStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timepoint_cpt", DbType="DateTime NOT NULL")]
		public System.DateTime timepoint_cpt
		{
			get
			{
				return this._timepoint_cpt;
			}
			set
			{
				if ((this._timepoint_cpt != value))
				{
					this._timepoint_cpt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lmp", DbType="Decimal(20,2) NOT NULL")]
		public decimal lmp
		{
			get
			{
				return this._lmp;
			}
			set
			{
				if ((this._lmp != value))
				{
					this._lmp = value;
				}
			}
		}
	}
	
	public partial class GetERCOTLocationsResult
	{
		
		private string _name;
		
		public GetERCOTLocationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class GetMax5minLMPTimepointResult
	{
		
		private System.Nullable<System.DateTime> _Column1;
		
		public GetMax5minLMPTimepointResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
