#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.DatabaseManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ISOStats")]
	public partial class ISOStatsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ISOStatsDataContext() : 
				base(global::Deg.DatabaseManager.Properties.Settings.Default.ISOStatsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ISOStatsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ISOStatsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ISOStatsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ISOStatsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ISOStats.dbo.GetRTLMPStartStop")]
		public ISingleResult<GetRTLMPStartStopResult> GetRTLMPStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(50)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="DateTime")] System.Nullable<System.DateTime> startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StopTime", DbType="DateTime")] System.Nullable<System.DateTime> stopTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publisher, startTime, stopTime);
			return ((ISingleResult<GetRTLMPStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ISOStats.dbo.GetDALMPStartStop")]
		public ISingleResult<GetDALMPStartStopResult> GetDALMPStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(50)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="DateTime")] System.Nullable<System.DateTime> startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StopTime", DbType="DateTime")] System.Nullable<System.DateTime> stopTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publisher, startTime, stopTime);
			return ((ISingleResult<GetDALMPStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ISOStats.dbo.GetMAXStatTime")]
		public ISingleResult<GetMAXStatTimeResult> GetMAXStatTime([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(50)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatType", DbType="VarChar(50)")] string statType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publisher, statType);
			return ((ISingleResult<GetMAXStatTimeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "ISOStats.dbo.GetISOLocations")]
		public ISingleResult<GetISOLocationsResult> GetISOLocations([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISO", DbType="VarChar(50)")] string iSO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iSO);
			return ((ISingleResult<GetISOLocationsResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetRTLMPStartStopResult
	{
		
		private string _Market;
		
		private System.Nullable<decimal> _VALUE;
		
		private System.DateTime _Timepoint;
		
		private string _Location;
		
		public GetRTLMPStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timepoint", DbType="DateTime NOT NULL")]
		public System.DateTime Timepoint
		{
			get
			{
				return this._Timepoint;
			}
			set
			{
				if ((this._Timepoint != value))
				{
					this._Timepoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
	}
	
	public partial class GetDALMPStartStopResult
	{
		
		private string _Market;
		
		private System.Nullable<decimal> _VALUE;
		
		private System.DateTime _Timepoint;
		
		private string _Location;
		
		public GetDALMPStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timepoint", DbType="DateTime NOT NULL")]
		public System.DateTime Timepoint
		{
			get
			{
				return this._Timepoint;
			}
			set
			{
				if ((this._Timepoint != value))
				{
					this._Timepoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
	}
	
	public partial class GetMAXStatTimeResult
	{
		
		private System.Nullable<System.DateTime> _Column1;
		
		public GetMAXStatTimeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetISOLocationsResult
	{
		
		private string _Location;
		
		public GetISOLocationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(100)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
