#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.DatabaseManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MISOExAnteLMPs")]
	public partial class MISO5minLMPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MISO5minLMPDataContext() : 
				base(global::Deg.DatabaseManager.Properties.Settings.Default.MISOExAnteLMPsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MISO5minLMPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MISO5minLMPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MISO5minLMPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MISO5minLMPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "MISOExAnteLMPs.dbo.GetMISO5minLMPStartStop")]
		public ISingleResult<GetMISO5minLMPStartStopResult> GetMISO5minLMPStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="DateTime")] System.Nullable<System.DateTime> startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StopTime", DbType="DateTime")] System.Nullable<System.DateTime> stopTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startTime, stopTime);
			return ((ISingleResult<GetMISO5minLMPStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "MISOExAnteLMPs.dbo.GetMISOLocations")]
		public ISingleResult<GetMISOLocationsResult> GetMISOLocations()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMISOLocationsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "MISOExAnteLMPs.dbo.GetMISOMaxTimepoint")]
		public ISingleResult<GetMISOMaxTimepointResult> GetMISOMaxTimepoint()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMISOMaxTimepointResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetMISO5minLMPStartStopResult
	{
		
		private string _NodeName;
		
		private System.DateTime _Timepoint;
		
		private System.Nullable<double> _LMP;
		
		private System.Nullable<System.DateTime> _EditTime;
		
		public GetMISO5minLMPStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this._NodeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timepoint", DbType="DateTime NOT NULL")]
		public System.DateTime Timepoint
		{
			get
			{
				return this._Timepoint;
			}
			set
			{
				if ((this._Timepoint != value))
				{
					this._Timepoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMP", DbType="Float")]
		public System.Nullable<double> LMP
		{
			get
			{
				return this._LMP;
			}
			set
			{
				if ((this._LMP != value))
				{
					this._LMP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditTime
		{
			get
			{
				return this._EditTime;
			}
			set
			{
				if ((this._EditTime != value))
				{
					this._EditTime = value;
				}
			}
		}
	}
	
	public partial class GetMISOLocationsResult
	{
		
		private string _location_name;
		
		public GetMISOLocationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string location_name
		{
			get
			{
				return this._location_name;
			}
			set
			{
				if ((this._location_name != value))
				{
					this._location_name = value;
				}
			}
		}
	}
	
	public partial class GetMISOMaxTimepointResult
	{
		
		private System.Nullable<System.DateTime> _Column1;
		
		public GetMISOMaxTimepointResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
