#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deg.DatabaseManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PJMInstantaneousDispatchRates")]
	public partial class PJMDispRates : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PJMDispRates() : 
				base(global::Deg.DatabaseManager.Properties.Settings.Default.PJMInstantaneousDispatchRatesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PJMDispRates(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PJMDispRates(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PJMDispRates(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PJMDispRates(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "PJMInstantaneousDispatchRates.dbo.GetDispRatesEdataStartStop")]
		public ISingleResult<GetDispRatesEdataStartStopResult> GetDispRatesEdataStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> stopTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startTime, stopTime);
			return ((ISingleResult<GetDispRatesEdataStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "PJMInstantaneousDispatchRates.dbo.GetDispRatesEdataTop")]
		public ISingleResult<GetDispRatesEdataTopResult> GetDispRatesEdataTop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), count);
			return ((ISingleResult<GetDispRatesEdataTopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "PJMInstantaneousDispatchRates.dbo.GetDispRatesWebpageStartStop")]
		public ISingleResult<GetDispRatesWebpageStartStopResult> GetDispRatesWebpageStartStop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="DateTime")] System.Nullable<System.DateTime> startTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StopTime", DbType="DateTime")] System.Nullable<System.DateTime> stopTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startTime, stopTime);
			return ((ISingleResult<GetDispRatesWebpageStartStopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "PJMInstantaneousDispatchRates.dbo.GetDispRatesWebpageTop")]
		public ISingleResult<GetDispRatesWebpageTopResult> GetDispRatesWebpageTop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), count);
			return ((ISingleResult<GetDispRatesWebpageTopResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetDispRatesEdataStartStopResult
	{
		
		private System.DateTime _TIMEPOINT;
		
		private System.DateTime _EDITTIME;
		
		private System.Nullable<float> _VALUE;
		
		private string _DATAZONE;
		
		public GetDispRatesEdataStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEPOINT", DbType="DateTime NOT NULL")]
		public System.DateTime TIMEPOINT
		{
			get
			{
				return this._TIMEPOINT;
			}
			set
			{
				if ((this._TIMEPOINT != value))
				{
					this._TIMEPOINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITTIME", DbType="DateTime NOT NULL")]
		public System.DateTime EDITTIME
		{
			get
			{
				return this._EDITTIME;
			}
			set
			{
				if ((this._EDITTIME != value))
				{
					this._EDITTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Real")]
		public System.Nullable<float> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAZONE", DbType="NVarChar(128)")]
		public string DATAZONE
		{
			get
			{
				return this._DATAZONE;
			}
			set
			{
				if ((this._DATAZONE != value))
				{
					this._DATAZONE = value;
				}
			}
		}
	}
	
	public partial class GetDispRatesEdataTopResult
	{
		
		private System.DateTime _TIMEPOINT;
		
		private System.DateTime _EDITTIME;
		
		private System.Nullable<float> _VALUE;
		
		private string _DATAZONE;
		
		public GetDispRatesEdataTopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEPOINT", DbType="DateTime NOT NULL")]
		public System.DateTime TIMEPOINT
		{
			get
			{
				return this._TIMEPOINT;
			}
			set
			{
				if ((this._TIMEPOINT != value))
				{
					this._TIMEPOINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITTIME", DbType="DateTime NOT NULL")]
		public System.DateTime EDITTIME
		{
			get
			{
				return this._EDITTIME;
			}
			set
			{
				if ((this._EDITTIME != value))
				{
					this._EDITTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Real")]
		public System.Nullable<float> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAZONE", DbType="NVarChar(128)")]
		public string DATAZONE
		{
			get
			{
				return this._DATAZONE;
			}
			set
			{
				if ((this._DATAZONE != value))
				{
					this._DATAZONE = value;
				}
			}
		}
	}
	
	public partial class GetDispRatesWebpageStartStopResult
	{
		
		private System.DateTime _TIMEPOINT;
		
		private System.DateTime _EDITTIME;
		
		private System.Nullable<float> _VALUE;
		
		private string _DATAZONE;
		
		public GetDispRatesWebpageStartStopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEPOINT", DbType="DateTime NOT NULL")]
		public System.DateTime TIMEPOINT
		{
			get
			{
				return this._TIMEPOINT;
			}
			set
			{
				if ((this._TIMEPOINT != value))
				{
					this._TIMEPOINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITTIME", DbType="DateTime NOT NULL")]
		public System.DateTime EDITTIME
		{
			get
			{
				return this._EDITTIME;
			}
			set
			{
				if ((this._EDITTIME != value))
				{
					this._EDITTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Real")]
		public System.Nullable<float> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAZONE", DbType="NVarChar(128)")]
		public string DATAZONE
		{
			get
			{
				return this._DATAZONE;
			}
			set
			{
				if ((this._DATAZONE != value))
				{
					this._DATAZONE = value;
				}
			}
		}
	}
	
	public partial class GetDispRatesWebpageTopResult
	{
		
		private System.DateTime _TIMEPOINT;
		
		private System.DateTime _EDITTIME;
		
		private System.Nullable<float> _VALUE;
		
		private string _DATAZONE;
		
		public GetDispRatesWebpageTopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEPOINT", DbType="DateTime NOT NULL")]
		public System.DateTime TIMEPOINT
		{
			get
			{
				return this._TIMEPOINT;
			}
			set
			{
				if ((this._TIMEPOINT != value))
				{
					this._TIMEPOINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITTIME", DbType="DateTime NOT NULL")]
		public System.DateTime EDITTIME
		{
			get
			{
				return this._EDITTIME;
			}
			set
			{
				if ((this._EDITTIME != value))
				{
					this._EDITTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Real")]
		public System.Nullable<float> VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAZONE", DbType="NVarChar(128)")]
		public string DATAZONE
		{
			get
			{
				return this._DATAZONE;
			}
			set
			{
				if ((this._DATAZONE != value))
				{
					this._DATAZONE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
